name: portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t portfolio:latest .

      # Log in to Docker Hub (optional, if you want to push)
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag portfolio:latest ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:latest

      # Run container (optional for testing in GitHub Actions)
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
